In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


mini batch gd = it is combination of batch and stoshicted we create the batch_size

**Batch Gradient Descent**: This method uses the entire dataset to calculate the gradient of the cost function. It's slow for large datasets but guarantees convergence to the minimum.

**Stochastic Gradient Descent (SGD)**: This method uses only one data point at a time to calculate the gradient. It's much faster than batch gradient descent but can have noisy updates and might not converge to the exact minimum.

**Mini-Batch Gradient Descent**: This method is a compromise between batch and stochastic gradient descent. It uses a small batch of data points (more than one, but less than the whole dataset) to calculate the gradient. This provides a good balance between speed and stability, making it a popular choice.
Think of it like this:

**Batch GD**: Taking a giant step based on looking at the whole landscape.
**SGD**: Taking tiny steps based on only looking at one spot at a time.
**Mini-Batch GD**: Taking moderate steps based on looking at a small area of the landscape.

In [2]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


In [3]:
X,y=load_diabetes(return_X_y=True)

In [4]:
X.shape


(442, 10)

In [5]:
y.shape


(442,)

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [7]:
reg=LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [8]:
y_pred=reg.predict(X_test)


In [9]:
r2_score(y_test,y_pred)

0.4399338661568968

In [10]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [11]:
reg.intercept_

np.float64(151.88331005254167)

In [14]:
class MBGDRegressor:

  def __init__(self,batch_size,learning_rate=0.01, epochs=100):
    self.coef_ = None
    self.intercept_ = None
    self.lr = learning_rate
    self.epochs = epochs
    self.batch_size=batch_size

  def fit(self, X_train, y_train):
    self.intercept_ = 0
    self.coef_ = np.ones(X_train.shape[1])

    for i in range(self.epochs):
      for j in range(int(X_train.shape[0]/self.batch_size)):
        idx=np.random.choice(X_train.shape[0],self.batch_size,replace=False)

        y_hat=np.dot(X_train[idx],self.coef_)+self.intercept_
        intercept_der=-2*np.mean(y_train[idx]-y_hat)
        self.intercept_=self.intercept_-(self.lr*intercept_der)
        coef_der=-2*np.dot((y_train[idx]-y_hat),X_train[idx])
        self.coef_=self.coef_-(self.lr*coef_der)

    print(self.intercept_,self.coef_)

  def predict(self, X_test):
    return np.dot(X_test, self.coef_) + self.intercept_

In [15]:
mbr=MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [16]:
mbr.fit(X_train,y_train)


150.9326029953964 [  29.24513826 -144.28034554  443.57395866  301.80598121  -24.3163039
  -94.15649383 -191.74016695  113.07465023  410.1130717   120.62143073]


In [17]:
y_pred=mbr.predict(X_test)

In [18]:
r2_score(y_test,y_pred)

0.45337774306410816

In [29]:
# by sklearn not have deafault class by using sgd
from sklearn.linear_model import SGDRegressor

In [36]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [37]:
batch_size = 35
import random

for i in range(100):

    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [38]:
sgd.coef_

array([  52.38955077,  -51.27290521,  305.14221328,  262.44499619,
         11.7912992 ,  -16.66943046, -184.16264903,  135.97858086,
        292.82341635,  117.15804792])

In [39]:
sgd.intercept_

array([156.49379621])

In [40]:
y_pred1=sgd.predict(X_test)

In [41]:
r2_score(y_test,y_pred1)

0.4213205279494169